from .final_frame_selector import (
    FinalFrameSelector, 
    NODE_CLASS_MAPPINGS as FINAL_FRAME_SELECTOR_MAPPINGS, 
    NODE_DISPLAY_NAME_MAPPINGS as FINAL_FRAME_SELECTOR_DISPLAY_MAPPINGS
)

from .video_merge import (
    VideoMerge,
    NODE_CLASS_MAPPINGS as VIDEO_MERGE_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as VIDEO_MERGE_DISPLAY_MAPPINGS
)

NODE_CLASS_MAPPINGS = {
    **FINAL_FRAME_SELECTOR_MAPPINGS,
    **VIDEO_MERGE_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **FINAL_FRAME_SELECTOR_DISPLAY_MAPPINGS,
    **VIDEO_MERGE_DISPLAY_MAPPINGS
}